"""
DeepEvolve interface for TIG Sigma II Job Scheduling challenge.
Generated from evaluator/deepevolve_interface.py by run.py.
Placeholders replaced at launch time by run.py.

DO NOT EDIT THIS FILE. DeepEvolve evolves rust_code.py only.
This file imports RUST_CODE from rust_code.py and handles build/test.
"""

import json
import os
import shutil
import subprocess
import sys
import time
import traceback
from pathlib import Path

from rich.console import Console
from rich.table import Table
from rich.panel import Panel
from rich import box as rich_box

_con = Console(stderr=True)

def _print(msg: str) -> None:
    """Print to stderr so output is visible even when stdout is redirected by DeepEvolve."""
    print(msg, file=sys.stderr, flush=True)

# ─── Configuration (filled by run.py) ────────────────────────────────────────
ALGO_NAME      = "__ALGO_NAME__"
ALGO_TYPE      = "__ALGO_TYPE__"
EVOLVE_MODE    = "__EVOLVE_MODE__"
EVOLVE_MODULE  = "__EVOLVE_MODULE__"
TRACKS         = __TRACKS__
NONCES         = __NONCES__
WORKERS        = __WORKERS__
HYPERPARAMS    = "__HYPERPARAMS__"  # dict: {track: hyperparams_string}
TIG_PATH       = "__TIG_PATH__"
DOCKER_IMAGE   = "__DOCKER_IMAGE__"
BASELINES      = __BASELINES__
BACKUPS_DIR    = Path("__BACKUPS_DIR__")

BASELINE_AVG   = sum(BASELINES.values()) / len(BASELINES) if BASELINES else 0.0
_RUST_CODE_ORIGINAL_LINE_COUNT = __RUST_CODE_ORIGINAL_LINES__

JSS_DIR        = Path(TIG_PATH) / "tig-algorithms" / "src" / "job_scheduling"

# ─── Import RUST_CODE from the evolved file ──────────────────────────────────
# rust_code.py is the file DeepEvolve modifies. We import it here so this
# interface always uses whatever the LLM has written.
from rust_code import RUST_CODE

def _get_current_best() -> float:
    """Read the current best combined_score from DeepEvolve's checkpoint."""
    try:
        best_info = Path(__file__).parent.parent / "ckpt" / "best" / "best_program_info.json"
        if best_info.exists():
            import json as _json
            data = _json.loads(best_info.read_text())
            return float(data.get("metrics", {}).get("combined_score", BASELINE_AVG))
    except Exception:
        pass
    return BASELINE_AVG

# ─── File resolution ──────────────────────────────────────────────────────────
def _algo_dir() -> Path:
    if ALGO_TYPE == "modular":
        return JSS_DIR / ALGO_NAME
    return JSS_DIR


# ─── Write evolved file to monorepo ──────────────────────────────────────────
def _write_evolved_file() -> None:
    """
    Write RUST_CODE into the monorepo.
    For modular algorithms: writes EVOLVE_MODULE inside the algorithm subdirectory.
    For single-file algorithms: writes ALGO_NAME.rs directly in the jss directory.
    """
    if EVOLVE_MODULE:
        dest = _algo_dir() / EVOLVE_MODULE
    else:
        # Single-file algorithm
        dest = JSS_DIR / f"{ALGO_NAME}.rs"
    dest.write_text(RUST_CODE, encoding="utf-8")

    # Ensure top-level mod.rs points to this algorithm
    top_mod = JSS_DIR / "mod.rs"
    top_mod.write_text(f"pub mod {ALGO_NAME};\n", encoding="utf-8")


# ─── Build ────────────────────────────────────────────────────────────────────
def _build() -> tuple:
    cmd = [
        "docker", "run", "--rm",
        "-v", f"{TIG_PATH}:/app",
        DOCKER_IMAGE,
        "bash", "-c", f"cargo clean && build_algorithm {ALGO_NAME}",
    ]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True,
                                timeout=300, stdin=subprocess.DEVNULL)
        if result.returncode != 0:
            stderr = result.stderr + result.stdout
            lines  = stderr.splitlines()
            blocks = []
            i = 0
            while i < len(lines):
                line = lines[i]
                if line.startswith("error[") or line.startswith("error:"):
                    block = [line]
                    j = i + 1
                    while j < len(lines) and j < i + 9:
                        if lines[j].startswith("error[") or lines[j].startswith("error:"):
                            break
                        block.append(lines[j])
                        j += 1
                    blocks.append("\n".join(block))
                    i = j
                else:
                    i += 1
            err = "\n\n".join(blocks[:8]) or stderr[-2000:]
            if len(blocks) > 8:
                err += f"\n\n... ({len(blocks)-8} more errors not shown)"
            return False, f"Build failed:\n{err}"
        return True, ""
    except subprocess.TimeoutExpired:
        return False, "Build timeout (300s)"
    except Exception as e:
        return False, f"Build exception: {e}"


# ─── Test a single track ──────────────────────────────────────────────────────
def _test_track(track: str, nonces: int, timeout_s: int = 600) -> dict:
    track_id    = f"n=50,s={track}"
    track_hyper = HYPERPARAMS.get(track, "null") if isinstance(HYPERPARAMS, dict) else HYPERPARAMS
    cmd = [
        "docker", "run", "--rm",
        "-v", f"{TIG_PATH}:/app",
        DOCKER_IMAGE,
        "test_algorithm", ALGO_NAME, track_id, track_hyper,
        "--nonces", str(nonces), "--workers", str(WORKERS),
    ]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True,
                                timeout=timeout_s, stdin=subprocess.DEVNULL)
        stdout = result.stdout + result.stderr

        if result.returncode != 0:
            return {"quality": 0.0, "time_s": 0.0, "success": False,
                    "invalid": False, "error": stdout[-800:]}

        quality = 0.0
        elapsed = 0.0
        for line in reversed(stdout.splitlines()):
            if "avg_quality:" in line and "#finished:" in line:
                try:
                    quality = float(line.split("avg_quality:")[-1].strip()
                                    .replace(",", "").split()[0])
                except Exception:
                    pass
                try:
                    elapsed = float(line.split("elapsed:")[-1].strip().split("s")[0])
                except Exception:
                    pass
                if quality != 0.0:
                    break

        for line in stdout.splitlines():
            if "#invalid:" in line:
                try:
                    n_inv = int(line.split("#invalid:")[-1].strip().split(",")[0])
                    if n_inv > 0:
                        return {"quality": 0.0, "time_s": elapsed, "success": False,
                                "invalid": True, "error": f"Invalid solution: {line.strip()}"}
                except Exception:
                    pass

        if "Invalid solution encountered" in stdout:
            return {"quality": 0.0, "time_s": elapsed, "success": False,
                    "invalid": True, "error": "Invalid solution encountered"}

        if quality == 0.0:
            return {"quality": 0.0, "time_s": elapsed, "success": False,
                    "invalid": False, "error": f"Could not parse quality:\n{stdout[-600:]}"}

        return {"quality": quality, "time_s": elapsed, "success": True,
                "invalid": False, "error": ""}

    except subprocess.TimeoutExpired:
        return {"quality": 0.0, "time_s": float(timeout_s), "success": False,
                "invalid": False, "error": f"Timeout ({timeout_s}s)"}
    except Exception as e:
        return {"quality": 0.0, "time_s": 0.0, "success": False,
                "invalid": False, "error": str(e)}


# ─── Backup evolved file ──────────────────────────────────────────────────────
def _backup_evolved_file(qualities: dict) -> None:
    """Back up the successfully evaluated evolved Rust code with timestamp and scores."""
    try:
        backup_algo_dir = BACKUPS_DIR / ALGO_NAME
        backup_algo_dir.mkdir(parents=True, exist_ok=True)

        ts = int(time.time())
        avg = sum(qualities.values()) / len(qualities) if qualities else 0.0
        score_str = f"avg{avg:.0f}"
        module_label = EVOLVE_MODULE.replace(".rs", "") if EVOLVE_MODULE else ALGO_NAME
        dest = backup_algo_dir / f"{ts}_{module_label}_{score_str}.rs"
        dest.write_text(RUST_CODE, encoding="utf-8")
        print(f"  Backup saved: backups/{ALGO_NAME}/{dest.name}")
    except Exception as e:
        print(f"  Warning: backup failed: {e}")


# ─── Main Interface ───────────────────────────────────────────────────────────
def deepevolve_interface():
    """
    Entry point called by DeepEvolve after each code evolution step.
    Returns (success: bool, metrics: dict | error_string: str).
    """
    t_start = time.time()

    _con.print()
    _con.print(Panel(
        f"[bold cyan]{ALGO_NAME}[/bold cyan]  ·  "
        f"Evolving: [bold]{EVOLVE_MODULE or 'full algorithm'}[/bold]  ·  "
        f"Tracks: [bold]{len(TRACKS)}[/bold]",
        title="[bold]Evaluation[/bold]",
        box=rich_box.ROUNDED,
        expand=False,
        padding=(0, 2),
    ))

    # ── Diagnostic: confirm RUST_CODE was actually modified ──
    rust_lines     = len(RUST_CODE.splitlines())
    original_lines = _RUST_CODE_ORIGINAL_LINE_COUNT
    if rust_lines == original_lines:
        _con.print(f"  [yellow]![/yellow]  RUST_CODE unchanged ({rust_lines} lines)")
    else:
        delta = rust_lines - original_lines
        _con.print(f"  [green]✓[/green]  RUST_CODE modified  "
                   f"([dim]{original_lines}[/dim] → [bold]{rust_lines}[/bold] lines, "
                   f"[{'green' if delta > 0 else 'red'}]{delta:+d}[/])")

    try:
        _write_evolved_file()

        ok, build_err = _build()
        if not ok:
            _con.print(f"  [red]✗[/red]  Build failed")
            _con.print(f"[red]{build_err}[/red]")
            return False, f"Build failed:\n{build_err}"

        _con.print(f"  [green]✓[/green]  Build successful\n")

        track_qualities = {}
        track_times     = {}
        track_invalid   = {}
        track_results   = {}

        for track in TRACKS:
            track_hyper = HYPERPARAMS.get(track, "null") if isinstance(HYPERPARAMS, dict) else HYPERPARAMS
            hyper_str = f", hyperparams={track_hyper}" if track_hyper and track_hyper != "null" else ""
            _con.print(f"  Testing [cyan]{track}[/cyan] ({NONCES} nonces{hyper_str})...", end="  ")
            res = _test_track(track, NONCES)
            track_qualities[track] = res["quality"]
            track_times[track]     = res["time_s"]
            track_invalid[track]   = res.get("invalid", False)
            track_results[track]   = res

            baseline  = BASELINES.get(track, 0.0)
            delta_pct = (res["quality"] - baseline) / max(baseline, 1.0) * 100.0
            if res.get("invalid"):
                _con.print(f"[red]INVALID[/red]")
            elif res["success"]:
                colour = "green" if delta_pct >= 0 else "red"
                _con.print(f"[green]OK[/green]  quality=[bold]{res['quality']:.0f}[/bold]  "
                           f"delta=[{colour}]{delta_pct:+.1f}%[/]")
            else:
                _con.print(f"[red]FAIL[/red]")

        _con.print()

        # ── Results table ──
        tbl = Table(box=rich_box.SIMPLE, show_header=True,
                    header_style="bold cyan", padding=(0, 2))
        tbl.add_column("Track")
        tbl.add_column("Status",   justify="center")
        tbl.add_column("Quality",  justify="right")
        tbl.add_column("Baseline", justify="right")
        tbl.add_column("Delta",    justify="right")
        tbl.add_column("Time",     justify="right")

        for track in TRACKS:
            res      = track_results[track]
            baseline = BASELINES.get(track, 0.0)
            delta_pct = (res["quality"] - baseline) / max(baseline, 1.0) * 100.0
            if track_invalid.get(track):
                status = "[red]INVALID[/red]"
                q_str  = "—"
                d_str  = f"[red]{delta_pct:+.1f}%[/red]"
            elif res["success"]:
                status = "[green]OK[/green]"
                q_str  = f"{res['quality']:,.0f}"
                colour = "green" if delta_pct >= 0 else "red"
                d_str  = f"[{colour}]{delta_pct:+.1f}%[/]"
            else:
                status = "[red]FAIL[/red]"
                q_str  = "—"
                d_str  = f"[red]{delta_pct:+.1f}%[/red]"
            tbl.add_row(
                track,
                status,
                q_str,
                f"{baseline:,.0f}",
                d_str,
                f"{res['time_s']:.1f}s",
            )

        _con.print(tbl)

        total_time = time.time() - t_start

        # Print error details for any INVALID or FAIL tracks
        problem_tracks = [t for t in TRACKS
                          if track_invalid.get(t, False) or not track_results[t]["success"]]
        if problem_tracks:
            for t in problem_tracks:
                err = track_results[t].get("error", "")
                if err:
                    _con.print(f"  [dim]{t:<20}  {err[:120]}[/dim]")
            _con.print()

        aborted = [t for t in TRACKS if track_invalid.get(t, False)]
        if aborted:
            _con.print(f"  [yellow]⚠[/yellow]  Invalid solutions on: "
                       f"[red]{', '.join(aborted)}[/red]  — score=0\n")
            metrics = {
                "combined_score":             0.0,
                "avg_quality":                0.0,
                "baseline_avg":               BASELINE_AVG,
                "improvement_over_baseline":  -BASELINE_AVG,
                "n_tracks_improved":          0.0,
                "total_time_s":               round(total_time, 2),
                "aborted_tracks":             ",".join(aborted),
                "evolved_module":             EVOLVE_MODULE or "full",
            }
            for t in TRACKS:
                metrics[f"quality_{t}"] = track_qualities.get(t, 0.0)
                metrics[f"time_{t}"]    = track_times.get(t, 0.0)
            return True, metrics

        avg_quality   = sum(track_qualities.values()) / max(len(track_qualities), 1)
        current_best  = _get_current_best()
        n_improved    = sum(1 for t, q in track_qualities.items()
                            if q > BASELINES.get(t, 0))
        delta_vs_best = avg_quality - current_best
        colour        = "green" if delta_vs_best >= 0 else "red"

        _con.print(f"  [bold]avg_quality[/bold]  {avg_quality:,.0f}  "
                   f"│  vs best: [{colour}]{delta_vs_best:+.0f}[/]  "
                   f"│  vs baseline: {avg_quality - BASELINE_AVG:+.0f}  "
                   f"│  tracks improved: {n_improved}/{len(TRACKS)}  "
                   f"│  time: {total_time:.1f}s\n")

        _backup_evolved_file(track_qualities)

        metrics = {
            "combined_score":             avg_quality,
            "avg_quality":                avg_quality,
            "current_best":               current_best,
            "delta_vs_best":              avg_quality - current_best,
            "original_baseline":          BASELINE_AVG,
            "improvement_over_baseline":  avg_quality - BASELINE_AVG,
            "n_tracks_improved":          float(n_improved),
            "total_time_s":               round(total_time, 2),
            "evolved_module":             EVOLVE_MODULE or "full",
        }
        for t in TRACKS:
            metrics[f"quality_{t}"]    = track_qualities.get(t, 0.0)
            metrics[f"time_{t}"]       = track_times.get(t, 0.0)
            baseline = BASELINES.get(t, 1.0)
            q = track_qualities.get(t, 0.0)
            metrics[f"delta_pct_{t}"]  = (q - baseline) / max(baseline, 1.0) * 100.0

        return True, metrics

    except Exception as e:
        err = traceback.format_exc()
        _con.print(f"[red]Exception: {type(e).__name__}: {e}[/red]")
        _con.print(f"[dim]{err}[/dim]")
        return False, f"Exception: {type(e).__name__}: {e}\n{err}"


if __name__ == "__main__":
    success, result = deepevolve_interface()
    _con.print(f"\n[bold]Success:[/bold] {success}")
    if isinstance(result, dict):
        for k, v in result.items():
            _print(f"  {k}: {v}")
    else:
        _print(f"Error: {result}")
